// ─── Taxonomy: 2-level hierarchy for the srvly catalog ───
// Main categories with their subcategories.

export interface TaxonomyCategory {
  id: string;          // machine key (e.g. "media")
  label: string;       // display name (e.g. "Media")
  icon: string;        // emoji icon
  description: string; // short description for category page
  subcategories: TaxonomySubcategory[];
}

export interface TaxonomySubcategory {
  id: string;    // machine key (e.g. "music")
  label: string; // display name (e.g. "Musique")
}

export const TAXONOMY: TaxonomyCategory[] = [
  {
    id: "media",
    label: "Media",
    icon: "🎬",
    description: "Applications pour gérer, streamer et organiser vos médias (musique, vidéo, photos, livres).",
    subcategories: [
      { id: "music", label: "Music" },
      { id: "video", label: "Video" },
      { id: "photos", label: "Photos" },
      { id: "books", label: "Books & Ebooks" },
      { id: "podcasts", label: "Podcasts" },
      { id: "media-management", label: "Media Management" },
    ],
  },
  {
    id: "dev-infra",
    label: "Dev & Infrastructure",
    icon: "🛠️",
    description: "Outils pour développeurs et infrastructure serveur : Docker, proxy, CI/CD, bases de données.",
    subcategories: [
      { id: "docker-containers", label: "Docker & Containers" },
      { id: "reverse-proxy", label: "Reverse Proxy" },
      { id: "cicd", label: "CI/CD" },
      { id: "database", label: "Database" },
      { id: "monitoring", label: "Monitoring" },
      { id: "git-code", label: "Git & Code" },
      { id: "ide-tools", label: "IDE & Dev Tools" },
      { id: "api-backend", label: "API & Backend" },
      { id: "server-management", label: "Server Administration" },
    ],
  },
  {
    id: "communication",
    label: "Communication",
    icon: "💬",
    description: "Solutions de communication : messagerie instantanée, email, forums et réseaux sociaux.",
    subcategories: [
      { id: "chat", label: "Chat & Messaging" },
      { id: "email", label: "Email" },
      { id: "forums", label: "Forums & Communities" },
      { id: "social", label: "Social Networks" },
    ],
  },
  {
    id: "security",
    label: "Security & Privacy",
    icon: "🔒",
    description: "Protection de votre infrastructure : VPN, authentification, mots de passe, pare-feu.",
    subcategories: [
      { id: "vpn-tunnel", label: "VPN & Tunnel" },
      { id: "auth-sso", label: "Authentication & SSO" },
      { id: "password-manager", label: "Password Managers" },
      { id: "firewall", label: "Firewall & Network" },
      { id: "secret-management", label: "Secret Management" },
    ],
  },
  {
    id: "productivity",
    label: "Productivity & Business",
    icon: "📋",
    description: "Applications pour le travail et la gestion : notes, wiki, CRM, finance, gestion de projet.",
    subcategories: [
      { id: "notes-wiki", label: "Notes & Wiki" },
      { id: "project-management", label: "Project Management" },
      { id: "crm-erp", label: "CRM & ERP" },
      { id: "finance", label: "Finance & Accounting" },
      { id: "documents", label: "Documents & PDF" },
      { id: "calendars", label: "Calendars & Planning" },
      { id: "forms-surveys", label: "Forms & Surveys" },
    ],
  },
  {
    id: "storage-backup",
    label: "Storage & Backup",
    icon: "💾",
    description: "Gestion des fichiers : partage, cloud personnel, sauvegardes et synchronisation.",
    subcategories: [
      { id: "file-sharing", label: "File Sharing" },
      { id: "cloud-storage", label: "Personal Cloud" },
      { id: "backup", label: "Backups" },
      { id: "sync", label: "Sync" },
    ],
  },
  {
    id: "automation-iot",
    label: "Automation & IoT",
    icon: "🤖",
    description: "Automatisation des tâches, workflows, domotique et objets connectés.",
    subcategories: [
      { id: "workflows", label: "Workflows & Automation" },
      { id: "smart-home", label: "Smart Home" },
      { id: "scraping", label: "Scraping & Crawling" },
    ],
  },
  {
    id: "gaming",
    label: "Gaming",
    icon: "🎮",
    description: "Serveurs de jeux, outils de gestion et streaming gaming.",
    subcategories: [
      { id: "game-servers", label: "Game Servers" },
      { id: "game-management", label: "Game Management" },
      { id: "streaming", label: "Gaming Streaming" },
    ],
  },
  {
    id: "ai-llm",
    label: "AI & LLM",
    icon: "🧠",
    description: "Intelligence artificielle : chatbots, agents autonomes, machine learning, bases vectorielles.",
    subcategories: [
      { id: "chat-assistant", label: "Chat & Assistant" },
      { id: "agents", label: "Autonomous Agents" },
      { id: "machine-learning", label: "Machine Learning" },
      { id: "vector-db", label: "Vector Databases" },
    ],
  },
  {
    id: "other",
    label: "Autres",
    icon: "📦",
    description: "Applications qui ne rentrent pas dans les catégories principales.",
    subcategories: [],
  },
];

// ─── Helpers ───

export function getCategory(id: string): TaxonomyCategory | undefined {
  return TAXONOMY.find((c) => c.id === id);
}

export function getSubcategory(categoryId: string, subId: string): TaxonomySubcategory | undefined {
  const cat = getCategory(categoryId);
  return cat?.subcategories.find((s) => s.id === subId);
}

/** Map old granular categories to new main categories */
const CATEGORY_MAP: Record<string, string> = {
  // → Media
  media: "media",
  music: "media",
  "music-streaming": "media",
  video: "media",
  photos: "media",
  "photo-management": "media",
  ebooks: "media",
  podcast: "media",
  audiobook: "media",
  "audiobook-server": "media",
  tv: "media",
  "tv-shows": "media",
  radio: "media",
  iptv: "media",
  "photo-gallery": "media",
  gallery: "media",
  "media-server": "media",
  "media-management": "media",
  "media-automation": "media",
  "media-manager": "media",
  "media-tracking": "media",

  // → Dev & Infrastructure
  "developer-tools": "dev-infra",
  docker: "dev-infra",
  "docker-compose": "dev-infra",
  "ci/cd": "dev-infra",
  database: "dev-infra",
  databases: "dev-infra",
  monitoring: "dev-infra",
  "network-monitoring": "dev-infra",
  observability: "dev-infra",
  "server-monitoring": "dev-infra",
  "system-monitoring": "dev-infra",
  "code-hosting": "dev-infra",
  ide: "dev-infra",
  "code-snippets": "dev-infra",
  "code-search": "dev-infra",
  "reverse-proxy": "dev-infra",
  proxy: "dev-infra",
  "api-gateway": "dev-infra",
  api: "dev-infra",
  backend: "dev-infra",
  "low-code": "dev-infra",
  "no-code": "dev-infra",
  "cloud-ide": "dev-infra",
  "cloud-management": "dev-infra",
  "cloud-computing": "dev-infra",
  "system-administration": "dev-infra",
  "server-management": "dev-infra",
  "container-management": "dev-infra",
  "admin-panels": "dev-infra",
  terminal: "dev-infra",
  "remote-desktop": "dev-infra",
  "remote-access": "dev-infra",
  "web-server": "dev-infra",
  dns: "dev-infra",
  "dns-management": "dev-infra",
  tunneling: "dev-infra",
  "bastion-host": "dev-infra",
  "data-science": "dev-infra",
  engineering: "dev-infra",
  "engineering-metrics": "dev-infra",
  "data-pipelines": "dev-infra",
  "data-analytics": "dev-infra",
  "data-management": "dev-infra",

  // → Communication
  chat: "communication",
  messaging: "communication",
  email: "communication",
  forum: "communication",
  forums: "communication",
  "social-networking": "communication",
  communication: "communication",
  "team-communication": "communication",
  voip: "communication",
  "video-conferencing": "communication",
  discord: "communication",
  whatsapp: "communication",
  newsletter: "communication",
  "email-marketing": "communication",
  "email-automation": "communication",
  "email-administration": "communication",

  // → Security
  security: "security",
  privacy: "security",
  vpn: "security",
  "password-manager": "security",
  authentication: "security",
  "identity-management": "security",
  "identity-and-access-management": "security",
  "identity-provider": "security",
  "secret-management": "security",
  "vulnerability-management": "security",
  "adguard-home": "security",

  // → Productivity & Business
  productivity: "productivity",
  notes: "productivity",
  "note-taking": "productivity",
  wiki: "productivity",
  "project-management": "productivity",
  crm: "productivity",
  erp: "productivity",
  finance: "productivity",
  "finance-management": "productivity",
  billing: "productivity",
  invoicing: "productivity",
  accounting: "productivity",
  "document-management": "productivity",
  documents: "productivity",
  pdf: "productivity",
  "pdf-management": "productivity",
  calendars: "productivity",
  calendar: "productivity",
  "appointment-scheduling": "productivity",
  forms: "productivity",
  "form-builder": "productivity",
  survey: "productivity",
  "time-tracking": "productivity",
  "task-management": "productivity",
  "human-resource-management": "productivity",
  "employee-onboarding": "productivity",
  "help-desk": "productivity",
  helpdesk: "productivity",
  "ticketing-system": "productivity",
  "customer-support": "productivity",
  "customer-feedback": "productivity",
  cms: "productivity",
  "headless-cms": "productivity",
  "content-management": "productivity",
  "asset-management": "productivity",
  "it-asset-management": "productivity",
  "itsm": "productivity",
  "reporting": "productivity",
  "business-intelligence": "productivity",
  "marketing-automation": "productivity",
  marketing: "productivity",
  "e-commerce": "productivity",
  "website-builder": "productivity",
  presentation: "productivity",
  design: "productivity",
  diagramming: "productivity",
  "documentation": "productivity",
  "knowledge-management": "productivity",
  "workspace-management": "productivity",
  "remote-collaboration": "productivity",
  collaboration: "productivity",
  "team-management": "productivity",
  "subscription-management": "productivity",
  "grocery-lists": "productivity",
  "recipe-management": "productivity",
  recipes: "productivity",
  fitness: "productivity",
  "habit-tracking": "productivity",
  diary: "productivity",
  journal: "productivity",
  "personal-relationship-manager": "productivity",
  "parenting": "productivity",
  "warranty-tracking": "productivity",
  "inventory": "productivity",
  "travel": "productivity",
  "gps-tracking": "productivity",
  "endurance-training": "productivity",
  "route-planning": "productivity",
  "investment-tracking": "productivity",
  "budget-management": "productivity",

  // → Storage & Backup
  "file-sharing": "storage-backup",
  "file-management": "storage-backup",
  "file-synchronization": "storage-backup",
  "file-storage": "storage-backup",
  "file-sync": "storage-backup",
  "file-manager": "storage-backup",
  "cloud-storage": "storage-backup",
  "object-storage": "storage-backup",
  backup: "storage-backup",
  "backup-management": "storage-backup",
  "file-processing": "storage-backup",
  "file-transfer": "storage-backup",
  archiving: "storage-backup",
  "secure-sharing": "storage-backup",
  sftp: "storage-backup",
  sync: "storage-backup",

  // → Automation & IoT
  automation: "automation-iot",
  "workflow-automation": "automation-iot",
  workflow: "automation-iot",
  "workflow-orchestration": "automation-iot",
  iot: "automation-iot",
  "smart-home": "automation-iot",
  "home-automation": "automation-iot",
  "web-scraping": "automation-iot",
  "web-crawling": "automation-iot",
  "browser-automation": "automation-iot",
  cron: "automation-iot",
  "task-monitoring": "automation-iot",

  // → Gaming
  gaming: "gaming",
  "game-server-management": "gaming",
  games: "gaming",
  steam: "gaming",
  twitch: "gaming",

  // → AI & LLM
  ai: "ai-llm",
  "ai-chat": "ai-llm",
  "large-language-models": "ai-llm",
  "language-models": "ai-llm",
  "machine-learning": "ai-llm",
  "ai-assistant": "ai-llm",
  chatgpt: "ai-llm",

  // → Otherwise keep as-is
};

export function mapToCategory(oldCategory: string | null): string {
  if (!oldCategory) return "other";
  const key = oldCategory.toLowerCase().trim();
  return CATEGORY_MAP[key] || "other";
}

/** Map old categories to subcategory based on heuristics */
const SUBCATEGORY_MAP: Record<string, string> = {
  music: "music",
  "music-streaming": "music",
  "music-management": "music",
  "music-bot": "music",
  video: "video",
  "video-management": "video",
  "video-editing": "video",
  photos: "photos",
  "photo-management": "photos",
  "photo-gallery": "photos",
  ebooks: "books",
  audiobook: "books",
  "audiobook-server": "books",
  podcast: "podcasts",
  "media-management": "media-management",
  "media-automation": "media-management",
  "media-server": "media-management",
  "media-manager": "media-management",
  "media-tracking": "media-management",
  docker: "docker-containers",
  "docker-compose": "docker-containers",
  "container-management": "docker-containers",
  "reverse-proxy": "reverse-proxy",
  proxy: "reverse-proxy",
  "ci/cd": "cicd",
  database: "database",
  databases: "database",
  "database-management": "database",
  "database-gui": "database",
  monitoring: "monitoring",
  "network-monitoring": "monitoring",
  "server-monitoring": "monitoring",
  "system-monitoring": "monitoring",
  observability: "monitoring",
  "code-hosting": "git-code",
  git: "git-code",
  "code-search": "git-code",
  ide: "ide-tools",
  "cloud-ide": "ide-tools",
  "code-snippets": "ide-tools",
  api: "api-backend",
  "api-gateway": "api-backend",
  backend: "api-backend",
  "server-management": "server-management",
  "system-administration": "server-management",
  chat: "chat",
  messaging: "chat",
  email: "email",
  forum: "forums",
  forums: "forums",
  "social-networking": "social",
  communication: "chat",
  vpn: "vpn-tunnel",
  tunneling: "vpn-tunnel",
  authentication: "auth-sso",
  "identity-management": "auth-sso",
  "identity-and-access-management": "auth-sso",
  "password-manager": "password-manager",
  "secret-management": "secret-management",
  "smart-home": "smart-home",
  "home-automation": "smart-home",
  iot: "smart-home",
  automation: "workflows",
  "workflow-automation": "workflows",
  workflow: "workflows",
  "web-scraping": "scraping",
  "web-crawling": "scraping",
  gaming: "game-servers",
  "game-server-management": "game-servers",
  ai: "chat-assistant",
  "ai-chat": "chat-assistant",
  "large-language-models": "machine-learning",
  "machine-learning": "machine-learning",
};

export function mapToSubcategory(oldCategory: string | null): string | null {
  if (!oldCategory) return null;
  const key = oldCategory.toLowerCase().trim();
  return SUBCATEGORY_MAP[key] || null;
}
