FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod ./
COPY . .
RUN go mod tidy && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /srvly-agent-linux-amd64 ./cmd/agent && \
    CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o /srvly-agent-linux-arm64 ./cmd/agent

FROM scratch
COPY --from=build /srvly-agent-linux-amd64 /srvly-agent-linux-amd64
COPY --from=build /srvly-agent-linux-arm64 /srvly-agent-linux-arm64
